language: node_js

node_js:
  - "stable"

services:
  - postgresql

addons:
  postgresql: "9.6"

cache:
  directories:
    - "node_modules"

before_install: cd ./Server

install:
  - npm install

before_script:
  - psql -c 'create database property_testdb;' -U postgres
  - psql -c "CREATE USER Admin WITH PASSWORD 'abdulateef';" -U postgres
  - "npm run create"

script:
  - npm run test

after_success: npm run coverage
