language: node_js

node_js:
  - "stable"

services:
  - postgresql

addons:
  postgresql: "9.6"

cache:
  directories:
    - "node_modules"

before_install: cd ./Server

env:
  global:
    - TOKEN_SECRET=juficasentimentalityandjabawockweezifeoluwapolorimitobegetikosefienuso

install:
  - npm install

before_script:
  - psql -c 'create database dbfor_test;' -U postgres

script:
  - npm run test

after_success: npm run coverage
